
-- Performance Lab: Database Schema (Robust Version)
-- Run this in your Supabase Dashboard > SQL Editor

-- 1. PROFILES (Public User Data)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  weight numeric,
  height numeric,
  age integer,
  gender text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

-- Policies (Drop first to avoid duplicates if re-running)
drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update their own profile." on profiles;
create policy "Users can update their own profile."
  on profiles for update
  using ( auth.uid() = id );

drop policy if exists "Users can select their own profile." on profiles;
create policy "Users can select their own profile."
  on profiles for select
  using ( auth.uid() = id );

-- 2. DAILY METRICS (Sleep, Mind, System)
create table if not exists daily_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  learning_mins integer default 0,
  screen_time_mins integer default 0,
  sleep_quality integer default 0,
  sleep_hours numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date)
);

alter table daily_metrics enable row level security;

drop policy if exists "Users can all on daily_metrics" on daily_metrics;
create policy "Users can all on daily_metrics"
  on daily_metrics for all
  using ( auth.uid() = user_id );

-- 3. NUTRITION LOGS (Macros & Calories)
create table if not exists nutrition_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  calories numeric default 0,
  protein numeric default 0,
  carbs numeric default 0,
  fats numeric default 0,
  junk_penalty numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date)
);

alter table nutrition_logs enable row level security;

drop policy if exists "Users can all on nutrition_logs" on nutrition_logs;
create policy "Users can all on nutrition_logs"
  on nutrition_logs for all
  using ( auth.uid() = user_id );

-- 4. TRAINING LOGS (Workouts)
create table if not exists training_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  exercise_name text not null,
  sets integer default 0,
  reps integer default 0,
  weight numeric default 0,
  volume_load numeric generated always as (sets * reps * weight) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table training_logs enable row level security;

drop policy if exists "Users can all on training_logs" on training_logs;
create policy "Users can all on training_logs"
  on training_logs for all
  using ( auth.uid() = user_id );
